theme: jekyll-theme-minimal
title: DevJourney Podcast
description: What if you could sit around a campfire ğŸ”¥ and listen to the world's best software developers tell you the tales of their life journeys? Welcome to Software Developer's Journey, the podcast shining a light ğŸ’¡ on developer's life from all around the globe ğŸŒ!
logo: /Img/logo.png
image: /Img/logo.png
author: Tim Bourguignon @timothep
show_downloads: false
twitter:
  username: devjourneyfm
  card: summary